datadiet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include("poll.urls")),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.conf.urls.static import static
from django.urls import path

from datadiet import settings
from poll import views

app_name = "poll"
urlpatterns = [
    path('', views.index, name="index"),
    path('<slug:department>', views.index, name="index"),
    path('<slug:department>/positions/', views.position_index, name="position-index"),
    path('<slug:department>/positions/<int:position_id>', views.position_detail, name="position-detail"),
    path('<slug:department>/positions/<int:position_id>/vote', views.vote, name="cast-vote"),
    path('<slug:department>/positions/<int:position_id>/vote/success', views.success, name="successful-vote"),
    path('results/', views.result_index, name="super-result-index"),
    path('results/list', views.result_list, name="super-result-list"),
    path('results/<int:position_id>', views.result_detail, name="result-detail"),
    path('super/', views.super_index, name="super-index"),
    path('super/login', views.login_user, name="super-login"),
    path('super/settings', views.my_settings, name="super-settings"),
    path('super/logout', views.logout_user, name="super-logout"),
    # path('super/department', views.super_department_index, name="super-position-index"),
    path('super/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position/add', views.super_position_add, name="super-position-add"),
    path('super/position/<int:position_id>', views.super_position_detail, name="super-position-detail"),
    path('super/position/<int:position_id>/edit', views.super_position_edit, name="super-position-edit"),
    path('super/position/<int:position_id>/delete', views.super_position_delete, name="super-position-delete"),
    path('super/nominee', views.super_nominee_index2, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee', views.super_nominee_index, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee/add', views.super_nominee_add, name="super-nominee-add"),
    path('super/position/nominee/add', views.super_nominee_add2, name="super-nominee-add"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>', views.super_nominee_detail,
         name="super-nominee-detail"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>/edit', views.super_nominee_edit,
         name="super-nominee-edit"),
    path('super/nominee/<int:nominee_id>/delete', views.super_nominee_delete, name="super-nominee-delete"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Department(models.Model):
    name=models.CharField(max_length=55)
    event_title=models.CharField(max_length=200,blank=True,null=True)
    description=models.CharField(max_length=200,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)
    start_date=models.DateTimeField(blank=True,null=True)
    end_date=models.DateTimeField(blank=True,null=True)
    vote_timeout=models.IntegerField(verbose_name="Vote timeout in hours",default=2)
    user=models.ManyToManyField(User)
    def __str__(self):
        return self.name

    def get_total_positions(self):

        return self.position_set.count()
    def get_total_nominees(self):
        sum=0
        return


class Position(models.Model):
    title=models.CharField(max_length=200)
    department=models.ForeignKey(Department, on_delete=models.CASCADE,blank=True,null=True)
    votes_count=models.IntegerField(default=0,blank=True,null=True)
    def __str__(self):

        return self.title + "[ "+self.department.__str__()+" ]"
    def get_winner(self):
        a=self.nominee_set.all().order_by('-votes').first()
        return a.get_fullname()


class Nominee(models.Model):
    position=models.ForeignKey(Position,on_delete=models.CASCADE,blank=True,null=True)
    first_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200)
    image=models.ImageField(null=True,blank=True)
    votes=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.get_fullname() + " going for " + self.position.title
    def get_fullname(self):
        return self.first_name + " " + self.last_name

class Settings(models.Model):
    start_date=models.DateTimeField(null=True)
    end_date=models.DateTimeField(null=True)

poll/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse, redirect, get_object_or_404
# Create your views here.
from django.template.response import TemplateResponse
from random import randrange

from poll.form import PositionForm, NomineeForm, SettingForm
from poll.models import Position, Nominee, Settings, Department


def alert(message):
    return {'alert_message':message}

def show_error404(request,message):
    return TemplateResponse(request,'poll/super/error_404.html',{'error_message':message})

def get_permissible_departments(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)
    return departments.values_list()


def get_expiry_date(department):
    department = department.upper()
    try:
        dept=Department.objects.get(name=department)
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}
    except Department.DoesNotExist:
        dept = Department.objects.get(name="DEFAULT")
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}

def update_ctx(ctx,department):
    department=department.upper()
    if ctx:
        ctx.update(get_expiry_date(department))
    else:
        ctx = get_expiry_date(department)
    return ctx

def index(request,department="default"):
    if department=='ascon':
        d=Department.objects.get(name='ASCON')
        positions=Position.objects.all().filter(department=d)
        ctx={'positions':positions,'home':'1'}
        update_ctx(ctx,'ascon')
        return TemplateResponse(request, "poll/default/default.html",ctx)
    return TemplateResponse(request, "poll/default/default.html", get_expiry_date(department))

    # return TemplateResponse(request, "poll/{}/index.html".format(department),get_expiry_date(department))

def position_index(request,department="default"):
    department = department.upper()
    try:
        position_list = Department.objects.get(name=department.upper())
        ctx = {"positions": position_list}
        if ctx:
            ctx.update(get_expiry_date(department))
        else:
            ctx = get_expiry_date(department)
        return TemplateResponse(request, "poll/default/default-position-index.html", ctx)
        # return TemplateResponse(request, "poll/{}/position-index.html".format(department), ctx)
    except Position.DoesNotExist:
        return HttpResponse("Page Not found")

def position_detail(request,department, position_id):
    try:
        position = Position.objects.get(pk=position_id)
        ctx = {"position": position}
        return TemplateResponse(request, "poll/default/default-positiion-detail.html", ctx)
    except Position.DoesNotExist:
        return HttpResponse("Doesn't Exist")

def vote(request,department, position_id):
    error_message = ""
    if request.method == "POST":
        if request.session.get('has_voted_{}'.format(position_id), 0):
            return TemplateResponse(request, "poll/default/error_voting.html", get_expiry_date())
            # return TemplateResponse(request, "poll/{}/error_voting.html".format(department),get_expiry_date())
        choice = request.POST["choice"]
        dept=Department.objects.get(name=department.upper())
        # request.session.set_expiry(int(os.environ.get('EXPIRY_SECONDS', 7200)))
        request.session.set_expiry(int(dept.vote_timeout)*3600)
        try:
            if not request.user.is_authenticated:
                request.session['has_voted_{}'.format(position_id)] = 1
                val = request.session.get_expiry_date().isoformat()
                request.session['expires_value_{}'.format(position_id)] = val
            nominee = Nominee.objects.get(pk=choice)
            nominee.votes += 1
            nominee.save()
            p = Position.objects.get(pk=position_id)
            p.votes_count += 1
            p.save()

        except Nominee.DoesNotExist:
            error_message = "Some error occurred"
        finally:
            if error_message:
                return redirect("poll:position-detail", position_id=position_id,department=department)
            return redirect("poll:successful-vote", position_id=position_id,department=department)
    else:

        if request.session.get('has_voted_{}'.format(position_id), 0):
            expir = request.session.get('expires_value_{}'.format(position_id), datetime.now().isoformat())
            ctx=update_ctx({'expires_at':expir},department)
            return TemplateResponse(request, "poll/default/error_voting.html", ctx)
            # return TemplateResponse(request, "{}/poll/error_voting.html".format(department),ctx)
        _obj = Position.objects.get(pk=position_id)
        ctx={"position": _obj}
        update_ctx(ctx,department)
        return TemplateResponse(request,"poll/default/default-positiion-detail.html",ctx)
        # return TemplateResponse(request, "poll/{}/position-detail.html".format(department), ctx)

def success(request,department, position_id):
    p = get_object_or_404(Position, pk=position_id)
    ctx=  {"position": p}
    update_ctx(ctx,department)
    # return TemplateResponse(request, "poll/{}/success.html".format(department), ctx)
    return TemplateResponse(request, "poll/default/default-success.html", ctx)


@login_required
def super_index(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)

    return TemplateResponse(request,'poll/super/super_index.html',{'departments':departments})

@login_required
def super_position_index(request,department_id='-1'):
    if department_id== "-1":
        return redirect('poll:super-index')
    try:
        department=get_object_or_404(Department,pk=department_id)
        # positions=Position.objects.all().filter(department=department)
        return TemplateResponse(request, 'poll/position/position_index.html', {'department': department})
    except Position.DoesNotExist:
        msg="Position does not exist"
        show_error404(request,msg)

@login_required
def super_position_add(request,department_id):
    form=PositionForm(request.POST or None)
    try:
        department=Department.objects.get(pk=department_id)
        if request.method == "POST":
            pos=Position()
            form=PositionForm(request.POST,instance=pos)
            if form.is_valid():
                new_form=form.save(commit=False)
                new_form.department = department
                new_form.save()

                return redirect('poll:super-position-index',department_id=department_id)
            else:
                return TemplateResponse(request, 'poll/position/position_add.html',
                                        {'form': form, 'department': department})
        else:
            return TemplateResponse(request, 'poll/position/position_add.html',
                                    {'form': form, 'department': department})
    except Department.DoesNotExist:
        msg='Department does not exist'
        show_error404(request,msg)


@login_required
def super_position_detail(request,position_id):
    return redirect("poll:super-position-edit",position_id=position_id)

@login_required
def super_position_delete(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")
    if request.method=="POST":
        position.delete()
        return redirect("poll:super-position-index")
    else:
        return TemplateResponse(request, 'poll/position/position_delete.html', {'position':position})

@login_required
def super_position_edit(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        da= position.department_id
        d=Department.objects.get(pk=da)
        form = PositionForm(request.POST or None, instance=position)
        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.department = d
                _f.save()
                return redirect('poll:super-position-index')
            else:
                return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})
        else:
            return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})

    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")

@login_required
def super_nominee_index2(request):
    u=get_object_or_404(User,username=request.user.username)
    d=Department.objects.get(user=u)
    p=d.position_set.all()
    return TemplateResponse(request, 'poll/nominee/nominee_index2.html', {'nominees':Nominee.objects.all(),'positions':p})

@login_required
def super_nominee_index(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request.POST, "Sorry, Position not found")
    return TemplateResponse(request, 'poll/nominee/nominee_index.html', {'position':position})

@login_required
def show_error(request,message):
    return TemplateResponse(request, 'poll/super/error_404.html', {'error_message':message})

@login_required
def super_nominee_add(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        form = NomineeForm(request.POST or None, request.FILES or None)

        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.position = position
                _f.save()

poll/templates/poll/position/position_add.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
Add Position
{% endblock %}


{% block content %}
        <div class="uk-container uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default uk-background-default ">
                <div class="uk-card-header">
                  <span class="uk-text uk-text-danger">{{ department.name|upper }} - </span>  Add a new Position here
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-3-3@m">
                      <form class="uk-form uk-form-horizontal" method="post" action="{% url 'poll:super-position-add' department.pk %}">
                          {% csrf_token %}
                          {{ form.errors }}
                       <div>Title :
                            {{ form.title }}</div>


<div class="uk-section">
    <button class="uk-button uk-button-default">Submit</button></div>

                    </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div>
        </div>
        </div>

{% endblock %}

poll/templates/poll/position/position_delete.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
    Delete Position
{% endblock %}


{% block content %}

    <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                    Sure to Delete {{ position.title }} ?
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-3-3">

    <p> Nominees affected : {{ position.nominee_set.all.count }} </p>
    <p> Please note that this is irreversible </p>
<form method="post" action="{% url 'poll:super-position-delete' position.pk %}">
    {% csrf_token %}
    <button class="uk-button uk-button-default tm-button-default" type="submit"> Confirm </button></form>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div>
        </div>
        </div>




{% endblock %}

poll/templates/poll/position/position_edit.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
Detail {{ nominee.get_fullname }}
{% endblock %}


{% block content %}
        <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                    Position Details
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-2-3@m">
                    <a class="uk-button uk-button-default" href="{% url 'poll:super-nominee-index' pk  %}"> View Nominees </a>
                    <a class="uk-button uk-button-primary" href="{% url 'poll:super-nominee-add' pk  %}"> Add Nominee </a>

                     <form class="uk-form" method="post" action="{% url 'poll:super-position-edit' pk %}">
{% if form.errors %}
<div class="uk-alert-danger" uk-alert>
    <a class="uk-alert-close" uk-close></a>
    <p>{{ form.errors }}.</p>
</div>
        {% endif %}
                          {% csrf_token %}
                        <label> Position :
                            {{ form.title }}
                        </label>
                        <br>
                        <br>
        <button class="uk-button uk-button-default" type="submit">Update</button>
    <button class="uk-button uk-button-default" type="reset">Clear</button>
    <a class="uk-button uk-button-danger" href="{% url 'poll:super-position-delete' pk  %}"> Delete </a>



                    </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div class="uk-flex-center uk-flex-middle uk-padding-small uk-width-1-3@m uk-text-center">
            <div class="uk-card uk-card-default">
                <span class="uk-h1"> {{ form.votes_count.value }}
                   </span>
                    <p>Total Votes </p>


            </div>
        </div>
        <div>
        </div>
        </div>

{% endblock %}

poll/templates/poll/position/position_index.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
Positions
{% endblock %}



{% block content %}

        <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-3-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                 <span class="uk-text uk-text-danger">{{ department.name|upper }} - </span>  All Positions
                </div>
                <div class="uk-card-body">
                    <div class="">
<table class="uk-table uk-table-small uk-table-hover uk-table-divider">
    <a class="uk-button uk-button-primary" href="{% url 'poll:super-position-add' department.pk %}"> Add Position </a>
    <a class="uk-button uk-button-muted" href="{% url 'poll:super-nominee-add' %}"> Add Nominee </a>
    <thead>
<tr>
<th>S/N</th>
<th>Title</th>
<th>Total Nominees</th>
<th>Total Votes </th>
</tr>
    </thead>
    {% for position in department.position_set.all|dictsort:"title"  %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'poll:super-position-edit' position.pk %}">{{ position.title }}</a></td>
        <td>{{ position.nominee_set.all.count}}</td>
        <td>{{ position.votes_count }}</td>
        <td> </td>
    </tr>
{% endfor %}

</table>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div>
        </div>
        </div>


{% endblock %}