datadiet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include("poll.urls")),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.conf.urls.static import static
from django.urls import path

from datadiet import settings
from poll import views

app_name = "poll"
urlpatterns = [
    path('', views.index, name="index"),
    path('<slug:department>', views.index, name="index"),
    path('<slug:department>/positions/', views.position_index, name="position-index"),
    path('<slug:department>/positions/<int:position_id>', views.position_detail, name="position-detail"),
    path('<slug:department>/positions/<int:position_id>/vote', views.vote, name="cast-vote"),
    path('<slug:department>/positions/<int:position_id>/vote/success', views.success, name="successful-vote"),
    path('results/', views.result_index, name="super-result-index"),
    path('results/list', views.result_list, name="super-result-list"),
    path('results/<int:position_id>', views.result_detail, name="result-detail"),
    path('super/', views.super_index, name="super-index"),
    path('super/login', views.login_user, name="super-login"),
    path('super/settings', views.my_settings, name="super-settings"),
    path('super/logout', views.logout_user, name="super-logout"),
    # path('super/department', views.super_department_index, name="super-position-index"),
    path('super/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position/add', views.super_position_add, name="super-position-add"),
    path('super/position/<int:position_id>', views.super_position_detail, name="super-position-detail"),
    path('super/position/<int:position_id>/edit', views.super_position_edit, name="super-position-edit"),
    path('super/position/<int:position_id>/delete', views.super_position_delete, name="super-position-delete"),
    path('super/nominee', views.super_nominee_index2, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee', views.super_nominee_index, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee/add', views.super_nominee_add, name="super-nominee-add"),
    path('super/position/nominee/add', views.super_nominee_add2, name="super-nominee-add"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>', views.super_nominee_detail,
         name="super-nominee-detail"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>/edit', views.super_nominee_edit,
         name="super-nominee-edit"),
    path('super/nominee/<int:nominee_id>/delete', views.super_nominee_delete, name="super-nominee-delete"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Department(models.Model):
    name=models.CharField(max_length=55)
    event_title=models.CharField(max_length=200,blank=True,null=True)
    description=models.CharField(max_length=200,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)
    start_date=models.DateTimeField(blank=True,null=True)
    end_date=models.DateTimeField(blank=True,null=True)
    vote_timeout=models.IntegerField(verbose_name="Vote timeout in hours",default=2)
    user=models.ManyToManyField(User)
    def __str__(self):
        return self.name

    def get_total_positions(self):

        return self.position_set.count()
    def get_total_nominees(self):
        sum=0
        return


class Position(models.Model):
    title=models.CharField(max_length=200)
    department=models.ForeignKey(Department, on_delete=models.CASCADE,blank=True,null=True)
    votes_count=models.IntegerField(default=0,blank=True,null=True)
    def __str__(self):

        return self.title + "[ "+self.department.__str__()+" ]"
    def get_winner(self):
        a=self.nominee_set.all().order_by('-votes').first()
        return a.get_fullname()


class Nominee(models.Model):
    position=models.ForeignKey(Position,on_delete=models.CASCADE,blank=True,null=True)
    first_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200)
    image=models.ImageField(null=True,blank=True)
    votes=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.get_fullname() + " going for " + self.position.title
    def get_fullname(self):
        return self.first_name + " " + self.last_name

class Settings(models.Model):
    start_date=models.DateTimeField(null=True)
    end_date=models.DateTimeField(null=True)

poll/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse, redirect, get_object_or_404
# Create your views here.
from django.template.response import TemplateResponse
from random import randrange

from poll.form import PositionForm, NomineeForm, SettingForm
from poll.models import Position, Nominee, Settings, Department


def alert(message):
    return {'alert_message':message}

def show_error404(request,message):
    return TemplateResponse(request,'poll/super/error_404.html',{'error_message':message})

def get_permissible_departments(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)
    return departments.values_list()


def get_expiry_date(department):
    department = department.upper()
    try:
        dept=Department.objects.get(name=department)
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}
    except Department.DoesNotExist:
        dept = Department.objects.get(name="DEFAULT")
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}

def update_ctx(ctx,department):
    department=department.upper()
    if ctx:
        ctx.update(get_expiry_date(department))
    else:
        ctx = get_expiry_date(department)
    return ctx

def index(request,department="default"):
    if department=='ascon':
        d=Department.objects.get(name='ASCON')
        positions=Position.objects.all().filter(department=d)
        ctx={'positions':positions,'home':'1'}
        update_ctx(ctx,'ascon')
        return TemplateResponse(request, "poll/default/default.html",ctx)
    return TemplateResponse(request, "poll/default/default.html", get_expiry_date(department))

    # return TemplateResponse(request, "poll/{}/index.html".format(department),get_expiry_date(department))

def position_index(request,department="default"):
    department = department.upper()
    try:
        position_list = Department.objects.get(name=department.upper())
        ctx = {"positions": position_list}
        if ctx:
            ctx.update(get_expiry_date(department))
        else:
            ctx = get_expiry_date(department)
        return TemplateResponse(request, "poll/default/default-position-index.html", ctx)
        # return TemplateResponse(request, "poll/{}/position-index.html".format(department), ctx)
    except Position.DoesNotExist:
        return HttpResponse("Page Not found")

def position_detail(request,department, position_id):
    try:
        position = Position.objects.get(pk=position_id)
        ctx = {"position": position}
        return TemplateResponse(request, "poll/default/default-positiion-detail.html", ctx)
    except Position.DoesNotExist:
        return HttpResponse("Doesn't Exist")

def vote(request,department, position_id):
    error_message = ""
    if request.method == "POST":
        if request.session.get('has_voted_{}'.format(position_id), 0):
            return TemplateResponse(request, "poll/default/error_voting.html", get_expiry_date())
            # return TemplateResponse(request, "poll/{}/error_voting.html".format(department),get_expiry_date())
        choice = request.POST["choice"]
        dept=Department.objects.get(name=department.upper())
        # request.session.set_expiry(int(os.environ.get('EXPIRY_SECONDS', 7200)))
        request.session.set_expiry(int(dept.vote_timeout)*3600)
        try:
            if not request.user.is_authenticated:
                request.session['has_voted_{}'.format(position_id)] = 1
                val = request.session.get_expiry_date().isoformat()
                request.session['expires_value_{}'.format(position_id)] = val
            nominee = Nominee.objects.get(pk=choice)
            nominee.votes += 1
            nominee.save()
            p = Position.objects.get(pk=position_id)
            p.votes_count += 1
            p.save()

        except Nominee.DoesNotExist:
            error_message = "Some error occurred"
        finally:
            if error_message:
                return redirect("poll:position-detail", position_id=position_id,department=department)
            return redirect("poll:successful-vote", position_id=position_id,department=department)
    else:

        if request.session.get('has_voted_{}'.format(position_id), 0):
            expir = request.session.get('expires_value_{}'.format(position_id), datetime.now().isoformat())
            ctx=update_ctx({'expires_at':expir},department)
            return TemplateResponse(request, "poll/default/error_voting.html", ctx)
            # return TemplateResponse(request, "{}/poll/error_voting.html".format(department),ctx)
        _obj = Position.objects.get(pk=position_id)
        ctx={"position": _obj}
        update_ctx(ctx,department)
        return TemplateResponse(request,"poll/default/default-positiion-detail.html",ctx)
        # return TemplateResponse(request, "poll/{}/position-detail.html".format(department), ctx)

def success(request,department, position_id):
    p = get_object_or_404(Position, pk=position_id)
    ctx=  {"position": p}
    update_ctx(ctx,department)
    # return TemplateResponse(request, "poll/{}/success.html".format(department), ctx)
    return TemplateResponse(request, "poll/default/default-success.html", ctx)


@login_required
def super_index(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)

    return TemplateResponse(request,'poll/super/super_index.html',{'departments':departments})

@login_required
def super_position_index(request,department_id='-1'):
    if department_id== "-1":
        return redirect('poll:super-index')
    try:
        department=get_object_or_404(Department,pk=department_id)
        # positions=Position.objects.all().filter(department=department)
        return TemplateResponse(request, 'poll/position/position_index.html', {'department': department})
    except Position.DoesNotExist:
        msg="Position does not exist"
        show_error404(request,msg)

@login_required
def super_position_add(request,department_id):
    form=PositionForm(request.POST or None)
    try:
        department=Department.objects.get(pk=department_id)
        if request.method == "POST":
            pos=Position()
            form=PositionForm(request.POST,instance=pos)
            if form.is_valid():
                new_form=form.save(commit=False)
                new_form.department = department
                new_form.save()

                return redirect('poll:super-position-index',department_id=department_id)
            else:
                return TemplateResponse(request, 'poll/position/position_add.html',
                                        {'form': form, 'department': department})
        else:
            return TemplateResponse(request, 'poll/position/position_add.html',
                                    {'form': form, 'department': department})
    except Department.DoesNotExist:
        msg='Department does not exist'
        show_error404(request,msg)


@login_required
def super_position_detail(request,position_id):
    return redirect("poll:super-position-edit",position_id=position_id)

@login_required
def super_position_delete(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")
    if request.method=="POST":
        position.delete()
        return redirect("poll:super-position-index")
    else:
        return TemplateResponse(request, 'poll/position/position_delete.html', {'position':position})

@login_required
def super_position_edit(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        da= position.department_id
        d=Department.objects.get(pk=da)
        form = PositionForm(request.POST or None, instance=position)
        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.department = d
                _f.save()
                return redirect('poll:super-position-index')
            else:
                return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})
        else:
            return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})

    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")

@login_required
def super_nominee_index2(request):
    u=get_object_or_404(User,username=request.user.username)
    d=Department.objects.get(user=u)
    p=d.position_set.all()
    return TemplateResponse(request, 'poll/nominee/nominee_index2.html', {'nominees':Nominee.objects.all(),'positions':p})

@login_required
def super_nominee_index(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request.POST, "Sorry, Position not found")
    return TemplateResponse(request, 'poll/nominee/nominee_index.html', {'position':position})

@login_required
def show_error(request,message):
    return TemplateResponse(request, 'poll/super/error_404.html', {'error_message':message})

@login_required
def super_nominee_add(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        form = NomineeForm(request.POST or None, request.FILES or None)

        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.position = position
                _f.save()

poll/templates/poll/super/base_admin.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %} - iVote</title>
        <meta charset="utf-8">
    <meta name="propeller" content="332436ab7c5e3627ad5560f7b4477d0a">
{#        <meta name="viewport" content="width=device-width, initial-scale=1">#}
        {% load staticfiles %}
    {% block scripts %}{% endblock %}
        <link rel="stylesheet" href="{% static 'poll/css/uikit.min.css' %}   " />
         <link rel="stylesheet" href="{% static 'poll/css/site.css' %} " />
        <script src="{% static 'poll/js/uikit.min.js' %} "></script>
        <script src="{% static 'poll/js/uikit-icons.min.js' %} "></script>

    </head>
    <body class="newhtml">
        <!-- Navigation Area -->
        <div class="uk-offcanvas-content" style="">
            <div class="uk-container-expand uk-light uk-background-primary color-lime uk-positidon-fixe" uk-navbar uk-sticky="bottom: #offset">
                <div class="uk-navbar-left">
                    <div class="uk-navbar-item"><span uk-icon="icon: 500px; ratio: 3.5"></span></div>
                         <div class="uk-navbar-item uk-text-bold">{{ DEPARTMENT.name|capfirst }} Admin Portal</div>
                </div>
                <div class="uk-navbar-right">
                    <div class="uk-navbar-item uk-visible@m"><a href="{% url 'poll:position-index' DEPARTMENT.name|lower|default:'default' %}" class="uk-link uk-text-primary"> Go to Site </a></div>
                    <div class="uk-navbar-item uk-text-bold uk-visible@m"> {{ request.user.username }} </div>
                    <div class="uk-navbar-item uk-visible@m"><a href="{% url 'poll:super-logout' %}" class="uk-button uk-button-default tm-button-default uk-text-bold" uk-icon="sign-out"> Sign Out  </a></div>
                    <a uk-navbar-toggle-icon="" href="#offcanvas" uk-toggle="" class="uk-navbar-toggle uk-hidden@m uk-navbar-toggle-icon uk-icon"><svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ratio="1"><rect y="9" width="20" height="2"></rect><rect y="3" width="20" height="2"></rect><rect y="15" width="20" height="2"></rect></svg></a>


                </div>
            </div>



        <!-- End of navigation -->

            <!-- Side Navigation  -->
              <div class="tm-sidebar-left color-lime fill uk-light uk-text-bold uk-visible@m" style="border-top:2px solid #fff;">
                <div class="uk-navbar">
                <ul class="uk-nav uk-nav-default">
                    <li class="uk-nav-header"> Dashboard</li>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-index' %}" > Event</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-position-index' %}" > Position</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-nominee-index' %}"> Nominee</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-result-index' %}"> Results</a>
                    <li class="uk-nav-divider"> <a href=""> Settings</a>
                </ul>
              </div>
              </div>

             <!-- End of Side Navigation  -->
        {% if alert_message %}
            <div class="uk-alert-warning" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <p>{{ alert_message }}</p>
            </div>
        {% endif %}
            {% block content %}
            {% endblock %}



        <div id="offcanvas" uk-offcanvas="mode: push; overlay: false" class="uk-offcanvas">
            <div class="uk-offcanvas-bar uk-background-default color-lime">
                <div class="uk-panel">
                    <ul class="uk-nav uk-nav-default">
                        <li class="uk-nav-header uk-text-uppercase">DASHBOARD
                                            <li class="uk-nav-divider"> <a href="{% url 'poll:super-position-index' %}" > Event</a>
                        <li class="uk-nav-divider"> <a href="{% url 'poll:super-position-index' %}" > Position</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-nominee-index' %}"> Nominee</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-result-index' %}"> Results</a>
                    <li class="uk-nav-divider"> <a href="{% url 'poll:super-result-index' %}"> Settings</a>
                    </ul>
                </div>
            </div>
        </div>
        </div>
    </body>

</html>

poll/templates/poll/super/department_edit.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
Edit Department
{% endblock %}

{% block content %}
        <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                    Department Details
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-2-3@m">
                     <form class="uk-form" method="post" action="{% url 'poll:super-position-edit' pk %}">
{% if form.errors %}
<div class="uk-alert-danger" uk-alert>
    <a class="uk-alert-close" uk-close></a>
    <p>{{ form.errors }}</p>
</div>
{% endif %}
                          {% csrf_token %}
                        <label> Position :
                            {{ form.title }}
                        </label>
                        <br>
<div class="uk-section">
        <button class="uk-button uk-button-default" type="submit">Update</button>
    <button class="uk-button uk-button-default" type="reset">Clear</button>

</div>

                    </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div class="uk-flex-center uk-flex-middle uk-padding-small uk-width-1-3@m uk-text-center">
            <div class="uk-card uk-card-default">
                <span class="uk-h1"> {{ form.votes_count.value }}
                   </span>
                    <p>Total Votes </p>


            </div>
        </div>
        <div>
        </div>
        </div>

{% endblock %}

poll/templates/poll/super/result_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>Title</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'poll/css/uikit.min.css' %}   " />
         <link rel="stylesheet" href="{% static 'poll/css/site.css' %} " />
        <script src="{% static 'poll/js/uikit.min.js' %} "></script>
        <script src="{% static 'poll/js/uikit-icons.min.js' %} "></script>
        <script src="{% static 'poll/js/Chart.bundle.min.js' %}"></script>
        <script src="{% static 'poll/js/jquery.min.js' %} "></script>
        <script src="{% static 'poll/js/datadiet.js' %} "></script>
            <style>
    canvas {
        -moz-user-select: none;
        -webkit-user-select: none;
        -ms-user-select: none;
    }
    </style>

    </head>
    <body>

<div class="uk-child-width-expand@m uk-text-center uk-grid-match fill" uk-grid>
    <div class="uk-flex-center color-lime uk-background@s uk-column-1-2 ">
        <div class="uk-container-large uk-light">
        <div class="uk-card-smal uk-animation-slide-left-medium">
            <div class="uk-card-header uk-text-bold">
                <p class="uk-h1"> Winner </p>
            </div>
            <div class="uk-card-body">
                {% if winner.image.url is not null %}
                <img src="{{ winner.image.url }}" class="uk-border-circle" width="200px" height="200px">
                {% else %}
                    {% load static %}
                <img src="{% static 'poll/images/photo.jpg' %}" class="uk-border-circle" width="200px" height="200px">
                {% endif %}
                <p>{{ winner.get_fullname }}</p>
                <p class="uk-text-bold"> {{ winner.position.title }}</p>
                <p> <span class="uk-text-bold"> {{ winner.votes }} Total Votes </span> </p>
                <a href="" class="uk-button uk-button-default tm-button-default">Back to Dashboard</a>
            </div>


        </div>
        </div>
    </div>



    <div class="uk-flex-center">
        <div class="uk-container">
            <h2 class="uk-h3">Metrics</h2>
            <canvas id="chart-area" width="190" height="190"></canvas>
            <script>
                var randomScalingFactor = function() {
            return Math.round(Math.random() * 100);
        };
                var config = {
            type: 'doughnut',
            data: {
                labels: {% autoescape off %}{{ user_data }}{% endautoescape %},
                datasets: [{
                    data:{{ data }},
                    label: 'Results',
                    backgroundColor: {% autoescape off %}{{ colors }}{% endautoescape %},
                }]
            },
            options: {
                responsive: true,
                legend:{ position : 'bottom'},
                animation: {
                    animateScale: true,
                    animateRotate: true
                }
            }
        };
                window.onload = function() {
            var ctx = document.getElementById('chart-area').getContext('2d');
            window.myDoughnut = new Chart(ctx, config);
        };
            </script>


        </div>
    </div>
    <div class="uk-flex-left">
        <div class="uk-container-expand">
            <div class="uk-card-small uk-align-left uk-card-body text-gold">
                <h2 class="uk-h2 text-gold uk-text-uppercase "> ASCON Awards</h2>
                <p class="uk-text-uppercase"> Vote Analysis for {{ position.title }}</p>
                <p class="uk-text-uppercase"> Total Votes = {{ position.votes_count }} </p>
               <div class="uk-grid-small uk-grid" uk-grid>
                   {% for nominee in position.nominee_set.all %}
                        <div class="uk-flex-inline uk-flex-middle uk-grid-margin uk-first-column">
                        {% if nominee.image.url is not null %}
                        {% load static %}
                            <img src="{{ nominee.image.url }}" class="uk-border-circle" width="40" height="40">
                            {% else %}
                            {% load static %}
                            <img src="{% static 'poll/images/photo.jpg' %}" class="uk-border-circle" width="40" height="40">
                            &nbsp;{% endif %}
                            <label>
                             {{ nominee.get_fullname }} -  {{ nominee.votes }} Votes
                            </label>
                        </div>
                   {% endfor %}
               </div>
                <div class="uk-card-footer">

<div class="uk-offcanvas-content">

    <!-- The whole page content goes here -->

    <button class="uk-button uk-button-default uk-margin-small-right tm-button-default" type="button" uk-toggle="target: #offcanvas-usage">Other Positions</button>
    <div id="offcanvas-usage" uk-offcanvas>
        <div class="uk-offcanvas-bar uk-background-default color-lime">

            <button class="uk-offcanvas-close" type="button" uk-close></button>

            <h3 class="uk-h3">Available results</h3>
            <div class="uk-container-small uk-align-center">
                <ul class="uk-navbar-nav uk-align-center uk-list-divider uk-height-small">
                    {% for p in positions %}
                    <li class="">
                    <a href="{% url 'poll:result-detail' p.pk %}" class="uk-button uk-button-default tm-button-default"> {{ p.title }}

                        <span uk-icon="check"></span></a>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>

</div>
                </div>
            </div>
        </div>
    </div>
</div>

    </body>
</html>

poll/templates/poll/super/result_index.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
    Result Page
{% endblock %}


{% block content %}

    <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                    Available results -  Click to display report
                    <a class="uk-button uk-button-danger" href="{% url 'poll:super-result-list' %}">Print all winners</a>
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-3-3">
                        <ul class="uk-list">
                            {% for position in positions %}

                                {% if position.votes_count > 0 %}
                            <li> {{ forloop.counter }}. <a href="{% url 'poll:result-detail' position.pk %} " class="uk">  {{ position.title }}  </a></li>
                           {% else %}
                            <li class="uk-text-muted"> {{ forloop.counter }}.  {{ position.title }} - No data available</li>
                            {% endif %}

                            {% endfor %}

                        </ul>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div>
        </div>
        </div>




{% endblock %}

poll/templates/poll/super/super_login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login - iVote</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'poll/css/uikit.min.css' %}   " />
         <link rel="stylesheet" href="{% static 'poll/css/site.css' %} " />
        <script src="{% static 'poll/js/uikit.min.js' %} "></script>
        <script src="{% static 'poll/js/uikit-icons.min.js' %} "></script>
    </head>
    <body>
<div class="uk-section fill base ">

        <div class="uk-container-expand ">
            <div class="uk-position-center uk-padding-large  ">
                <div class="uk-card uk-card-default uk-card-large@m uk-width-large@m uk-text-center">
                    <div class="uk-card-header"> <h3 class="uk-h2">Superuser </h3></div>
                    <div class="uk-card-body uk-padding-remove-top ">
        <form class="uk-form-large@m uk-padding-small" action="{% url 'poll:super-login' %}" method="post">
            {% if error_message %}
                  <div class="uk-text-warning " > {{ error_message }} </div>
            {% endif %}
        {% csrf_token %}
        <div class="uk-inline uk-margin-medium-top">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
            <input class="uk-input" type="text" name="username">
        </div>
        <div class="uk-inline uk-margin-medium-top   ">
            <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
            <input class="uk-input" type="password" name="password">
            </div><div class="uk-card-footer">
<button class="uk-button uk-button-default tm-button-default base uk-light"  type="submit"  >    Get me in </button>
</div>
                        </form>
                    </div>


                </div>
            </div>

 </div>


            <div class="uk-position-bottom uk-overlay uk-overlay-default uk-text-center" >  Copyright @ Anonymous 2018 </div>



        </div>






    </body>
    </html>

poll/templates/poll/super/super_settings.html
{% extends 'poll/super/base_admin.html' %}

{% block title %}
    Settings
{% endblock %}


{% block scripts %}
    {% load static %}
         <link rel="stylesheet" href="{% static 'poll/css/bootstrap-datetimepicker.min.css' %}   " />

{% endblock %}

{% block content %}

    <div class="uk-child-width-expand@m uk-grid-match tm-container " uk-grid>
        <div class="uk-width-2-3@m uk-padding-small">
            <div class="">
              <div class="uk-card uk-card-default  uk-background-default ">
                <div class="uk-card-header">
                    Settings Module
                </div>
                <div class="uk-card-body">
                    <div class="uk-width-3-3">

    <p> Configure Appropriately</p>
<form method="post" action="{% url 'poll:super-settings' %}">
    {% csrf_token %}
<label> Vote start Period
    <div class="for_datetime">{{ form.start_date }}</div>

</label>
    <label> Vote Stop Period
            <div class="for_datetime">{{ form.end_date }}</div>

</label>
<script type="text/javascript">
  $(function() {
    $('.form_datetime').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>

    <button class="uk-button uk-button-default tm-button-default" type="submit"> Update </button></form>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div>
        </div>
        </div>




{% endblock %}