datadiet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include("poll.urls")),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.conf.urls.static import static
from django.urls import path

from datadiet import settings
from poll import views

app_name = "poll"
urlpatterns = [
    path('', views.index, name="index"),
    path('<slug:department>', views.index, name="index"),
    path('<slug:department>/positions/', views.position_index, name="position-index"),
    path('<slug:department>/positions/<int:position_id>', views.position_detail, name="position-detail"),
    path('<slug:department>/positions/<int:position_id>/vote', views.vote, name="cast-vote"),
    path('<slug:department>/positions/<int:position_id>/vote/success', views.success, name="successful-vote"),
    path('results/', views.result_index, name="super-result-index"),
    path('results/list', views.result_list, name="super-result-list"),
    path('results/<int:position_id>', views.result_detail, name="result-detail"),
    path('super/', views.super_index, name="super-index"),
    path('super/login', views.login_user, name="super-login"),
    path('super/settings', views.my_settings, name="super-settings"),
    path('super/logout', views.logout_user, name="super-logout"),
    # path('super/department', views.super_department_index, name="super-position-index"),
    path('super/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position', views.super_position_index, name="super-position-index"),
    path('super/<int:department_id>/position/add', views.super_position_add, name="super-position-add"),
    path('super/position/<int:position_id>', views.super_position_detail, name="super-position-detail"),
    path('super/position/<int:position_id>/edit', views.super_position_edit, name="super-position-edit"),
    path('super/position/<int:position_id>/delete', views.super_position_delete, name="super-position-delete"),
    path('super/nominee', views.super_nominee_index2, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee', views.super_nominee_index, name="super-nominee-index"),
    path('super/position/<int:position_id>/nominee/add', views.super_nominee_add, name="super-nominee-add"),
    path('super/position/nominee/add', views.super_nominee_add2, name="super-nominee-add"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>', views.super_nominee_detail,
         name="super-nominee-detail"),
    path('super/position/<int:position_id>/nominee/<int:nominee_id>/edit', views.super_nominee_edit,
         name="super-nominee-edit"),
    path('super/nominee/<int:nominee_id>/delete', views.super_nominee_delete, name="super-nominee-delete"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Department(models.Model):
    name=models.CharField(max_length=55)
    event_title=models.CharField(max_length=200,blank=True,null=True)
    description=models.CharField(max_length=200,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)
    start_date=models.DateTimeField(blank=True,null=True)
    end_date=models.DateTimeField(blank=True,null=True)
    vote_timeout=models.IntegerField(verbose_name="Vote timeout in hours",default=2)
    user=models.ManyToManyField(User)
    def __str__(self):
        return self.name

    def get_total_positions(self):

        return self.position_set.count()
    def get_total_nominees(self):
        sum=0
        return


class Position(models.Model):
    title=models.CharField(max_length=200)
    department=models.ForeignKey(Department, on_delete=models.CASCADE,blank=True,null=True)
    votes_count=models.IntegerField(default=0,blank=True,null=True)
    def __str__(self):

        return self.title + "[ "+self.department.__str__()+" ]"
    def get_winner(self):
        a=self.nominee_set.all().order_by('-votes').first()
        return a.get_fullname()


class Nominee(models.Model):
    position=models.ForeignKey(Position,on_delete=models.CASCADE,blank=True,null=True)
    first_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200)
    image=models.ImageField(null=True,blank=True)
    votes=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.get_fullname() + " going for " + self.position.title
    def get_fullname(self):
        return self.first_name + " " + self.last_name

class Settings(models.Model):
    start_date=models.DateTimeField(null=True)
    end_date=models.DateTimeField(null=True)

poll/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse, redirect, get_object_or_404
# Create your views here.
from django.template.response import TemplateResponse
from random import randrange

from poll.form import PositionForm, NomineeForm, SettingForm
from poll.models import Position, Nominee, Settings, Department


def alert(message):
    return {'alert_message':message}

def show_error404(request,message):
    return TemplateResponse(request,'poll/super/error_404.html',{'error_message':message})

def get_permissible_departments(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)
    return departments.values_list()


def get_expiry_date(department):
    department = department.upper()
    try:
        dept=Department.objects.get(name=department)
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}
    except Department.DoesNotExist:
        dept = Department.objects.get(name="DEFAULT")
        return {'EXPIRY_DATE': dept.end_date, 'START_DATE': dept.start_date,'DEPARTMENT':dept}

def update_ctx(ctx,department):
    department=department.upper()
    if ctx:
        ctx.update(get_expiry_date(department))
    else:
        ctx = get_expiry_date(department)
    return ctx

def index(request,department="default"):
    if department=='ascon':
        d=Department.objects.get(name='ASCON')
        positions=Position.objects.all().filter(department=d)
        ctx={'positions':positions,'home':'1'}
        update_ctx(ctx,'ascon')
        return TemplateResponse(request, "poll/default/default.html",ctx)
    return TemplateResponse(request, "poll/default/default.html", get_expiry_date(department))

    # return TemplateResponse(request, "poll/{}/index.html".format(department),get_expiry_date(department))

def position_index(request,department="default"):
    department = department.upper()
    try:
        position_list = Department.objects.get(name=department.upper())
        ctx = {"positions": position_list}
        if ctx:
            ctx.update(get_expiry_date(department))
        else:
            ctx = get_expiry_date(department)
        return TemplateResponse(request, "poll/default/default-position-index.html", ctx)
        # return TemplateResponse(request, "poll/{}/position-index.html".format(department), ctx)
    except Position.DoesNotExist:
        return HttpResponse("Page Not found")

def position_detail(request,department, position_id):
    try:
        position = Position.objects.get(pk=position_id)
        ctx = {"position": position}
        return TemplateResponse(request, "poll/default/default-positiion-detail.html", ctx)
    except Position.DoesNotExist:
        return HttpResponse("Doesn't Exist")

def vote(request,department, position_id):
    error_message = ""
    if request.method == "POST":
        if request.session.get('has_voted_{}'.format(position_id), 0):
            return TemplateResponse(request, "poll/default/error_voting.html", get_expiry_date())
            # return TemplateResponse(request, "poll/{}/error_voting.html".format(department),get_expiry_date())
        choice = request.POST["choice"]
        dept=Department.objects.get(name=department.upper())
        # request.session.set_expiry(int(os.environ.get('EXPIRY_SECONDS', 7200)))
        request.session.set_expiry(int(dept.vote_timeout)*3600)
        try:
            if not request.user.is_authenticated:
                request.session['has_voted_{}'.format(position_id)] = 1
                val = request.session.get_expiry_date().isoformat()
                request.session['expires_value_{}'.format(position_id)] = val
            nominee = Nominee.objects.get(pk=choice)
            nominee.votes += 1
            nominee.save()
            p = Position.objects.get(pk=position_id)
            p.votes_count += 1
            p.save()

        except Nominee.DoesNotExist:
            error_message = "Some error occurred"
        finally:
            if error_message:
                return redirect("poll:position-detail", position_id=position_id,department=department)
            return redirect("poll:successful-vote", position_id=position_id,department=department)
    else:

        if request.session.get('has_voted_{}'.format(position_id), 0):
            expir = request.session.get('expires_value_{}'.format(position_id), datetime.now().isoformat())
            ctx=update_ctx({'expires_at':expir},department)
            return TemplateResponse(request, "poll/default/error_voting.html", ctx)
            # return TemplateResponse(request, "{}/poll/error_voting.html".format(department),ctx)
        _obj = Position.objects.get(pk=position_id)
        ctx={"position": _obj}
        update_ctx(ctx,department)
        return TemplateResponse(request,"poll/default/default-positiion-detail.html",ctx)
        # return TemplateResponse(request, "poll/{}/position-detail.html".format(department), ctx)

def success(request,department, position_id):
    p = get_object_or_404(Position, pk=position_id)
    ctx=  {"position": p}
    update_ctx(ctx,department)
    # return TemplateResponse(request, "poll/{}/success.html".format(department), ctx)
    return TemplateResponse(request, "poll/default/default-success.html", ctx)


@login_required
def super_index(request):
    user=get_object_or_404(User,username=request.user.username)
    departments = Department.objects.all().filter(user=user)

    return TemplateResponse(request,'poll/super/super_index.html',{'departments':departments})

@login_required
def super_position_index(request,department_id='-1'):
    if department_id== "-1":
        return redirect('poll:super-index')
    try:
        department=get_object_or_404(Department,pk=department_id)
        # positions=Position.objects.all().filter(department=department)
        return TemplateResponse(request, 'poll/position/position_index.html', {'department': department})
    except Position.DoesNotExist:
        msg="Position does not exist"
        show_error404(request,msg)

@login_required
def super_position_add(request,department_id):
    form=PositionForm(request.POST or None)
    try:
        department=Department.objects.get(pk=department_id)
        if request.method == "POST":
            pos=Position()
            form=PositionForm(request.POST,instance=pos)
            if form.is_valid():
                new_form=form.save(commit=False)
                new_form.department = department
                new_form.save()

                return redirect('poll:super-position-index',department_id=department_id)
            else:
                return TemplateResponse(request, 'poll/position/position_add.html',
                                        {'form': form, 'department': department})
        else:
            return TemplateResponse(request, 'poll/position/position_add.html',
                                    {'form': form, 'department': department})
    except Department.DoesNotExist:
        msg='Department does not exist'
        show_error404(request,msg)


@login_required
def super_position_detail(request,position_id):
    return redirect("poll:super-position-edit",position_id=position_id)

@login_required
def super_position_delete(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")
    if request.method=="POST":
        position.delete()
        return redirect("poll:super-position-index")
    else:
        return TemplateResponse(request, 'poll/position/position_delete.html', {'position':position})

@login_required
def super_position_edit(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        da= position.department_id
        d=Department.objects.get(pk=da)
        form = PositionForm(request.POST or None, instance=position)
        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.department = d
                _f.save()
                return redirect('poll:super-position-index')
            else:
                return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})
        else:
            return TemplateResponse(request, 'poll/position/position_edit.html', {'form': form, 'pk': position_id})

    except Position.DoesNotExist:
        return show_error(request, "Sorry, Position not found")

@login_required
def super_nominee_index2(request):
    u=get_object_or_404(User,username=request.user.username)
    d=Department.objects.get(user=u)
    p=d.position_set.all()
    return TemplateResponse(request, 'poll/nominee/nominee_index2.html', {'nominees':Nominee.objects.all(),'positions':p})

@login_required
def super_nominee_index(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
    except Position.DoesNotExist:
        return show_error(request.POST, "Sorry, Position not found")
    return TemplateResponse(request, 'poll/nominee/nominee_index.html', {'position':position})

@login_required
def show_error(request,message):
    return TemplateResponse(request, 'poll/super/error_404.html', {'error_message':message})

@login_required
def super_nominee_add(request,position_id):
    try:
        position=Position.objects.get(pk=position_id)
        form = NomineeForm(request.POST or None, request.FILES or None)

        if request.method == "POST":
            if form.is_valid():
                _f = form.save(commit=False)
                _f.position = position
                _f.save()

poll/templates/poll/default/base.html
{% load settings %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}: 3D-Awards{% endblock %}</title>
        <meta charset="utf-8">
    <meta name="propeller" content="332436ab7c5e3627ad5560f7b4477d0a">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'poll/css/uikit.min.css' %}   " />
         <link rel="stylesheet" href="{% static 'poll/css/site.css' %} " />
        <script src="{% static 'poll/js/uikit.min.js' %} "></script>
        <script src="{% static 'poll/js/uikit-icons.min.js' %} "></script>
        <script src="{% static 'poll/js/jquery.min.js' %} "></script>
        <script src="{% static 'poll/js/datadiet.js' %} "></script>
    </head>
    <body>

<div class="uk-grid-collapse uk-child-width-expand@m uk-text-center uk-grid-match fill uk-child-width-expand@s uk-child-width-expand@l" uk-grid>
    <div class="uk-flex uk-flex-center">
        <div class="uk-background-contain uk-height-large uk-panel" style="background-image: url({% static 'poll/images/2d.jpeg' %});">
        <div class="uk-section"></div>
        <div class="uk-section"></div>
        <div class="uk-section"></div>
        <div class="uk-section-xsmall"> 
                <span uk-spinner="ratio:2"></span>
        </div>
        {% now 'c' as the_time %}
            {% if EXPIRY_DATE|date:'c' < the_time %}
        <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ EXPIRY_DATE|date:'c'}}">
        {% elif START_DATE|date:'c' > the_time %}
            <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ START_DATE|date:'c'}}">
        {% else %}
            <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ EXPIRY_DATE|date:'c'}}">
        {% endif %}
    <div>
        <div class="uk-countdown-number uk-countdown-days text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Days</div>
    </div>
    <div class="uk-countdown-separator">:</div>
    <div>
        <div class="uk-countdown-number uk-countdown-hours text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Hours</div>
    </div>
    <div class="uk-countdown-separator">:</div>
    <div>
        <div class="uk-countdown-number uk-countdown-minutes text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Minutes</div>
    </div>
    <div class="uk-countdown-separator">:</div>
    <div>
        <div class="uk-countdown-number uk-countdown-seconds text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Seconds</div>
    </div> 
        </div>
       </div>
    </div>
    <div class="uk-flex uk-flex-center">

        <div class="uk-background color-lime uk-padding uk-light uk-background-fixed">
            <div class="uk-container uk-container">
           <h3 class="uk-h2 uk-margin-bottom-remove"> Faculty of Communication and Information Sciences </h3>
            {% if DEPARTMENT.name != "DEFAULT" %}
           <br/>  {{ DEPARTMENT.name|capfirst }} Section </div>

            {% endif %}
            </h3>
            <p class="uk-h3"><a href="{% url 'poll:index' DEPARTMENT.name|lower %}" class="uk-text-muted">Voting Portal</a>  </p>
                <p class=""> The much awaited {{ DEPARTMENT.event_title }},</p>
            {% now 'c' as timer %}
            {% if EXPIRY_DATE|date:'c' < timer %}
                {% include "poll/default/expired_voting.html" with error_message='Sorry, Voting has closed'%}
            {% elif START_DATE|date:'c' > timer %}
                {% include "poll/default/expired_voting.html" with error_message='Stay tuned, awards opening soon.'%}
            {% else %}
                {% block content %}
                {% endblock %}
            {% endif %}

            </div>
        </div>
    </div>
</div>

    </body>
</html>

poll/templates/poll/default/base_default.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  <meta name="propeller" content="332436ab7c5e3627ad5560f7b4477d0a">

    <title>
        {% if DEPARTMENT.name %}
                {{ DEPARTMENT.name|upper }} DECIDES
                {% else %}
                iDecide
            {% endif %}
    {% block title %}
    {% endblock %}

    </title>
      {% load staticfiles %}
{% block scripts %}
  {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'poll/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'poll/css/uikit.min.css' %}   " />
    <!-- Custom styles for this template -->
    <link href="{% static 'poll/css/one-page-wonder.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'poll/css/site.css' %} "/>
  </head>

  <body>
    <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark color-lime fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'poll:index' DEPARTMENT.name|lower %}">
            {% if DEPARTMENT.name %}
                {{ DEPARTMENT.name|upper }} DECIDES
                {% else %}
                iDecide
            {% endif %}
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'poll:index' DEPARTMENT.name|lower %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
        {% now 'c' as the_time %}
            {% if EXPIRY_DATE|date:'c' < the_time %}
                <li class="nav-item"><a class="nav-link" href="#">Voting(Closed)</a></li>
        {% elif START_DATE|date:'c' > the_time %}
                <li class="nav-item"><a class="nav-link" href="#">Voting(Pending)</a></li>
        {% else %}
                <li class="nav-item"><a class="nav-link active" href="{% url 'poll:position-index' DEPARTMENT.name|lower  %}">Proceed to Vote</a></li>
        {% endif %}


          </ul>
        </div>
      </div>
    </nav>
{% if not home %}
        <header class="masthead">
      <div class="overlay">
        <div class="container">

          <p class=" text-white "> {{ position.department.description }} </p>
                  <p class=" text-white">{{ position.title }}</p>

            {% if EXPIRY_DATE|date:'c' < the_time %}
        <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ EXPIRY_DATE|date:'c'}}">
        {% elif START_DATE|date:'c' > the_time %}
            <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ START_DATE|date:'c'}}">
        {% else %}
            <div class="uk-section-xsmall uk-grid-small uk-flex-center" uk-grid uk-countdown="date: {{ EXPIRY_DATE|date:'c'}}">
        {% endif %}
    <div class="text-white">
        <div class="uk-countdown-number uk-countdown-days text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Days</div>
    </div>
    <div class="uk-countdown-separator text-white">:</div>
    <div class="text-white">
        <div class="uk-countdown-number uk-countdown-hours text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Hours</div>
    </div>
    <div class="uk-countdown-separator text-white">:</div>
    <div class="text-white">
        <div class="uk-countdown-number uk-countdown-minutes text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Minutes</div>
    </div>
    <div class="uk-countdown-separator text-white">:</div>
    <div class="text-white">
        <div class="uk-countdown-number uk-countdown-seconds text-color"></div>
        <div class="uk-countdown-label uk-margin-xsmall uk-text-center uk-visible@s">Seconds</div>
    </div>
        </div>

        </div>
      </div>
        <script type="text/javascript" src="//go.oclasrv.com/apu.php?zoneid=1969359"></script>
    </header>
{% endif %}
    {% block home_content %}
    {% endblock %}
    {% if EXPIRY_DATE|date:'c' < the_time %}

        {% include "poll/default/expired_voting.html" with error_message='Sorry, Voting has closed'%}
    {% elif START_DATE|date:'c' > the_time %}
        {% include "poll/default/expired_voting.html" with error_message='Stay tuned, voting opening soon.'%}
    {% else %}
        {% block content %}

        {% endblock %}




    {% endif %}






{#  {% block content %}#}
{##}
{#  {% endblock %}#}
<!-- Footer -->
    <section>
<div class="container">
    <div class="row">
    <div class="uk-card uk-card-default uk-card-body uk-card-hover uk-width-1-1">
        <script async="async" data-cfasync="false" src="//native.propellerads.com/1?z=1969431&eid="></script>
</div>
</div>
</div>

</section>
    <footer class="py-5 color-lime">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Azeem and Oseni 2019</p>
      </div>
      <!-- /.container -->
    </footer>



   {% load staticfiles %}



    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'poll/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'poll/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'poll/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
          <script src="{% static 'poll/js/uikit.min.js' %} "></script>
        <script src="{% static 'poll/js/uikit-icons.min.js' %} "></script>
        <script src="{% static 'poll/js/datadiet.js' %} "></script>

  </body>


</html>

poll/templates/poll/default/default-positiion-detail.html
{% extends 'poll/default/base_default.html' %}

{% block title %}
    - {{ position.title }}
{% endblock %}


{% block content %}
        <section>
<form>
      <div class="container" >
        <div class="row">
    <div class="uk-width-1-1">
        <div class="uk=card uk-card-default uk-hover uk-padding">
            <div class="uk-card-title"><h3 class="uk-text-primary"><span uk-icon="info"></span> {{ position.title }} ... </h3></div>
            <div class="uk-card-footer">
                <div class="uk-child-width-1-3@s uk-grid-match" uk-grid>
   {% for nominee in position.nominee_set.all|dictsort:"first_name" %}
   <div>
    <div class="uk-card uk-card-small uk-card-default uk-card-hover">
    <div class="uk-card-title uk-margin-remove ">
                            {% if nominee.image %}
            <img src="{{ nominee.image.url }}" class="uk-border-circle uk-align-middle">
            &nbsp;
            {% else %}
                {% load static %}
            <img src="{% static 'poll/images/photo.jpg' %}" class="uk-border-circle uk-align-center">
            &nbsp;
            {% endif %}
    </div>
    <div class="uk-card-footer">
                <h4 class="card-title text-center uk-text-danger">{{ nominee.get_fullname }}</h4>

              <a disabled="false" class="uk-align-center uk-button uk-button-danger confirm" related="{{ nominee.get_fullname }}" nominee="{{ nominee.pk }}"> Vote </a>

    </div>
    </div>
    </div>
   {% endfor %}
</div>
            </div>

        </div>


    </div>
          </div>

        </div>
</form>
    </section>

    <div id="modal-confirm" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-margin-auto-vertical">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <div class="uk-modal-header">
            <h2 class="uk-modal-title">Confirm Nomination</h2>
        </div>
        <div class="uk-modal-body">
            <p>You selected <span id="selectedName"> </span>  for the {{ position.title }} award.</p>
            <p>Confirm selection</p>
        </div>
                <form>
            <input hidden name="userChoice" value="" id="submit">
        </form>
        <div class="uk-modal-footer uk-text-right">
            <form method="post" action="{% url 'poll:cast-vote' DEPARTMENT.name|lower position.pk %}">
                        {% csrf_token %}
            <input hidden name="choice" value="" id="userChoice">
            <button class="uk-button uk-button-default uk-modal-close canc" type="button">Cancel</button>
            <button class="uk-button uk-button-danger color-lime" id="btnFinalSub" type="submit">Submit</button>
        </form>
        </div>
    </div>
</div>
    <div id="modal-center" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">

        <button class="uk-modal-close-default" type="button" uk-close></button>
<div class="uk-align-center">
Oops, seems like you forgot to pick a lucky nominee
            <br> this and pick the one
            <br>Cheers </div>
    </div>
</div>

{% endblock %}

poll/templates/poll/default/default-position-index.html
{% extends 'poll/default/base_default.html' %}

{% block title %}
     Pick a Category
{% endblock %}

{% block content %}
        <section>
      <div class="container">
      <div class="uk-card uk-card-default uk-padding-small">
          <div class="uk-card-title uk-padding"> <h3> <span class="uk-text-danger" uk-icon="database"> </span> Select a category </h3>  </div>
          <div class="uk-card-footer">
                <div class="uk-child-width-1-3@s uk-grid-match" uk-grid>
          {% for position in positions.position_set.all|dictsort:"title" %}
    <div>
        <div class="uk-card uk-card-default uk-card-hover uk-card-body">
            <h3 class="uk-card-title"><a href="{% url 'poll:cast-vote' DEPARTMENT.name|lower position.pk %}" class="uk-link-text">{{ position.title }}</a></h3>
    <p class="uk-text-right"> {{ position.votes_count }} <span class="uk-text-danger">Total Votes</span></p>
        </div>
    </div>
          {% endfor %}
      </div>
          </div>

      </div>
        </div>
    </section>

{% endblock %}

poll/templates/poll/default/expired_voting.html
<section>
<div class="container">
    <div class="row">
    <div class="uk-card uk-card-default uk-card-body uk-card-hover uk-width-1-1">
  <h3 class="uk-h3 uk-center uk-text-danger"> {{ error_message }} </h3>
        <p>
              <a href="{% url 'poll:position-index' DEPARTMENT.name|lower %}" class=" uk-button uk-button-danger"> Back to portal </a>
        </p>
</div>
</div>
</div>

</section>